export const KEY_ENUM = {
  C_MAJOR: 'C Major',
  G_MAJOR: 'G Major',
  D_MAJOR: 'D Major',
  A_MAJOR: 'A Major',
  E_MAJOR: 'E Major',
  B_MAJOR: 'B Major',
  F_SHARP_MAJOR: 'F# Major',
  C_SHARP_MAJOR: 'C# Major',
  F_MAJOR: 'F Major',
  B_FLAT_MAJOR: 'Bb Major',
  E_FLAT_MAJOR: 'Eb Major',
  A_FLAT_MAJOR: 'Ab Major',
  D_FLAT_MAJOR: 'Db Major',
  G_FLAT_MAJOR: 'Gb Major',
  A_MINOR: 'A Minor',
  E_MINOR: 'E Minor',
  B_MINOR: 'B Minor',
  F_SHARP_MINOR: 'F# Minor',
  C_SHARP_MINOR: 'C# Minor',
  G_SHARP_MINOR: 'G# Minor',
  D_SHARP_MINOR: 'D# Minor',
  A_SHARP_MINOR: 'A# Minor',
  D_MINOR: 'D Minor',
  G_MINOR: 'G Minor',
  C_MINOR: 'C Minor',
  F_MINOR: 'F Minor',
  B_FLAT_MINOR: 'Bb Minor',
  E_FLAT_MINOR: 'Eb Minor',
};

export const METER_ENUM = {
  FOUR_FOUR: '4/4',
  THREE_FOUR: '3/4',
  SIX_EIGHT: '6/8',
  FIVE_FOUR: '5/4',
  SEVEN_EIGHT: '7/8',
};
