"""empty message

Revision ID: 2f0ce451bf48
Revises: c329f10f8020
Create Date: 2025-07-04 13:51:41.391265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0ce451bf48'
down_revision = 'c329f10f8020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('instrument')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
