"""empty message

Revision ID: 313b8548af9b
Revises: 2f0ce451bf48
Create Date: 2025-07-04 14:07:19.573295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313b8548af9b'
down_revision = '2f0ce451bf48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tracks_instrument_id', 'instruments', ['instrument_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('instrument_id')

    # ### end Alembic commands ###
