"""empty message

Revision ID: 629429d9441c
Revises: 4b7a7660c546
Create Date: 2025-07-01 00:31:48.198591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '629429d9441c'
down_revision = '4b7a7660c546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('roles')
        batch_op.drop_column('is_active')
        batch_op.drop_column('instruments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instruments', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('roles', sqlite.JSON(), nullable=False))

    # ### end Alembic commands ###
