"""empty message

Revision ID: 85ff820a2d6a
Revises: 5eb8e10a3492
Create Date: 2025-07-13 16:07:32.887503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ff820a2d6a'
down_revision = '5eb8e10a3492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_track_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('main_track_url')

    # ### end Alembic commands ###
