"""empty message

Revision ID: 993b35169042
Revises: baef585ae9db
Create Date: 2025-06-27 16:54:32.506817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993b35169042'
down_revision = 'baef585ae9db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
